apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secplat.fullname" . }}-config
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
data:
{{- $config := omit .Values.config "API_URL" "OPENSEARCH_URL" "REDIS_URL" "INGESTION_OS_URL" }}
  API_URL: {{ include "secplat.apiUrl" . | quote }}
  OPENSEARCH_URL: {{ include "secplat.opensearchUrl" . | quote }}
  REDIS_URL: {{ include "secplat.redisUrl" . | quote }}
  INGESTION_OS_URL: {{ include "secplat.opensearchUrl" . | quote }}
{{- range $key, $value := $config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secplat.fullname" . }}-secrets
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
type: Opaque
stringData:
{{- $secretData := omit .Values.secretData "API_POSTGRES_DSN" "API_MIGRATIONS_POSTGRES_DSN" }}
  API_POSTGRES_DSN: {{ include "secplat.apiPostgresDsn" . | quote }}
  API_MIGRATIONS_POSTGRES_DSN: {{ include "secplat.migrationsPostgresDsn" . | quote }}
{{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
