{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secplat.serviceAccountName" . }}
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
automountServiceAccountToken: false
{{- end }}
