apiVersion: v1
kind: Service
metadata:
  name: {{ include "secplat.fullname" . }}-api
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-api
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secplat.fullname" . }}-worker-web
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-worker-web
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-worker-web
  ports:
    - name: metrics
      port: {{ .Values.workerWeb.service.port }}
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secplat.fullname" . }}-correlator
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-correlator
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-correlator
  ports:
    - name: metrics
      port: {{ .Values.correlator.service.port }}
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secplat.fullname" . }}-notifier
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-notifier
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-notifier
  ports:
    - name: metrics
      port: {{ .Values.notifier.service.port }}
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secplat.fullname" . }}-deriver
  namespace: {{ include "secplat.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-deriver
    app.kubernetes.io/part-of: {{ include "secplat.name" . }}
{{ include "secplat.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "secplat.fullname" . }}-deriver
  ports:
    - name: metrics
      port: {{ .Values.deriver.service.port }}
      targetPort: metrics
