apiVersion: v1
kind: Service
metadata:
  name: secplat-notifier
  namespace: secplat
  labels:
    app.kubernetes.io/name: secplat-notifier
    app.kubernetes.io/part-of: secplat
spec:
  selector:
    app.kubernetes.io/name: secplat-notifier
  ports:
    - name: metrics
      port: 9103
      targetPort: metrics
