apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: secplat-worker-web
  namespace: secplat
  labels:
    app.kubernetes.io/name: secplat-worker-web
    app.kubernetes.io/part-of: secplat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: secplat-worker-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
