apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: secplat
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: secplat
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: metrics
      port: 8888
      targetPort: metrics
