apiVersion: v1
kind: Service
metadata:
  name: secplat-worker-web
  namespace: secplat
  labels:
    app.kubernetes.io/name: secplat-worker-web
    app.kubernetes.io/part-of: secplat
spec:
  selector:
    app.kubernetes.io/name: secplat-worker-web
  ports:
    - name: metrics
      port: 9101
      targetPort: metrics
